---
abstract: 'Provides a Geo-Coding functionality using free databases'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  App::csv2sqlite: '0'
  CGI::IDS: '0'
  CGI::Lingua: '0'
  CHI: '0'
  CHI::Driver::RawMemory: '0'
  Data::Throttler: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Spec: '0'
  IPC::System::Simple: '0'
  JSON: '0'
  LWP::UserAgent::Throttled: '0'
  Test::Carp: '0'
  Test::Most: '0'
  Test::NoWarnings: '0'
  Test::Number::Delta: '0'
  autodie: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::Fetch: '0.56'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-Coder-Free
no_index:
  directory:
    - t
    - inc
requires:
  CHI: '0'
  DBD::CSV: '0'
  DBD::SQLite: '0'
  DBI: '0'
  Digest::MD5: '0'
  Encode: '0'
  File::Spec: '0'
  File::Temp: '0'
  File::pfopen: '0.02'
  Geo::StreetAddress::US: '0'
  Gzip::Faster: '0'
  List::MoreUtils: '0'
  Locale::CA: '0'
  Locale::Country: '0'
  Locale::SubCountry: '0'
  Locale::US: '0'
  Module::Info: '0'
  Storable: '0'
  Text::CSV: '0'
  perl: '5.006002'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Geo-Coder-Free
  repository: git://github.com/nigelhorne/Geo-Coder-Free.git
version: '0.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
